name: GeoGAD
channels:
  - milagraph
  - pytorch
  - pyg
  - bioconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohappyeyeballs=2.4.0=py38h06a4308_0
  - aiohttp=3.10.5=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aom=3.6.1=h59595ed_0
  - aria2=1.37.0=hbc8128a_2
  - async-timeout=4.0.3=py38h06a4308_0
  - attrs=24.2.0=py38h06a4308_0
  - bio-embeddings-esm=0.2.1=pyhd8ed1ab_0
  - biopython=1.79=py38h0a891b7_3
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cached-property=1.5.2=py_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2024.8.30=py38h06a4308_0
  - chardet=5.2.0=py38h578d9bd_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - clifford=1.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h7f3f72f_1
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.53.1=py38h2019614_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.4.0=py38h5eee18b_0
  - fsspec=2024.6.1=py38h06a4308_0
  - gawk=5.3.1=hcd3d067_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.7.9=hb077bed_0
  - greenlet=3.0.3=py38h17151c0_0
  - h5py=3.11.0=nompi_py38h55b5aab_102
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hmmer=3.4=h503566f_3
  - icu=75.1=he02047a_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.4=py38h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_0
  - lddt=2.2=h9ee0642_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h6a678d5_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=16_linux64_mkl
  - libboost=1.84.0=hb8260a3_6
  - libboost-python=1.84.0=py38haa4b4a7_5
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=0
  - libcurl=8.10.1=hbbe4b11_0
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.21=h4bc722e_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.82.2=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=12.2.5.2=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.6.68=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=16.4=h2d7952a_3
  - librdkit=2024.03.5=h79cfef2_3
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=h6565414_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.13.1=h6a678d5_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hb9d3cd8_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.41.1=py38h94a1851_0
  - matplotlib-base=3.7.3=py38h58ed7fa_0
  - mkl=2022.1.0=hc2b9512_224
  - mmseqs2=15.6f452=pl5321h6a68c12_3
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=py38h06a4308_0
  - multidict=6.0.4=py38h5eee18b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.1=py38h06a4308_0
  - numba=0.58.1=py38h4144172_0
  - numpy=1.24.4=py38h59b608b_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.0.3=py38h01efb38_1
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - pillow=10.4.0=py38h2bc05a7_0
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.2=h59595ed_0
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.7.0=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycairo=1.26.1=py38he403b34_0
  - pyg=2.6.1=py38_torch_2.4.0_cu124
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=h4a871b0_1_cpython
  - python-lmdb=1.5.1=py38h79ccf07_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=5_cp38
  - pytorch=2.4.1=py3.8_cuda12.4_cudnn9.1.0_0
  - pytorch-cluster=1.6.3=py38_torch_2.4.0_cu124
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py38_torch_2.4.0_cu124
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.1=py38h5eee18b_0
  - rdkit=2024.03.5=py38h890d753_3
  - readline=8.2=h8228510_1
  - reportlab=4.2.2=py38hfb59056_0
  - requests=2.32.3=py38h06a4308_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scipy=1.10.1=py38h59b608b_3
  - six=1.16.0=pyh6c4a22f_0
  - sparse=0.15.5=pyh72ffeb9_0
  - sqlalchemy=2.0.32=py38h2019614_0
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.13.2=py38h06a4308_0
  - tbb=2021.13.0=h84d6215_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.4.1=py38_cu124
  - torchdrug=0.2.1=h6066fbd
  - torchtriton=3.0.0=py38
  - torchvision=0.19.1=py38_cu124
  - unicodedata2=15.1.0=py38h01eb140_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.3=hb9d3cd8_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py38h5eee18b_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - antiberty==0.1.3
      - astor==0.8.1
      - cachetools==5.5.0
      - click==8.1.8
      - cliffordlayers==0.1.1
      - cloudpickle==3.1.0
      - easydict==1.13
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - fair-esm==2.0.1
      - filelock==3.11.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.35.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.66.1
      - huggingface-hub==0.27.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - markdown==3.7
      - markupsafe==2.1.5
      - mock==5.1.0
      - ninja==1.11.1.3
      - nni==3.0
      - nvidia-ml-py==12.560.30
      - oauthlib==3.2.2
      - pluggy==1.5.0
      - prettytable==3.11.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pythonwebhdfs==0.2.3
      - rdkit-pypi==2022.9.5
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - responses==0.25.3
      - rsa==4.9
      - safetensors==0.4.5
      - schema==0.7.7
      - scikit-learn==1.3.2
      - seaborn==0.13.2
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - setuptools==59.5.0
      - simplejson==3.19.3
      - smmap==5.0.2
      - subword-nmt==0.3.8
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - typeguard==4.1.2
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - wandb==0.20.1
      - wcwidth==0.2.13
      - websockets==13.1
      - werkzeug==3.0.4
